-- Run this in the Supabase SQL editor to create the storage bucket.
-- The bucket is private — all access goes through signed URLs
-- generated by the service-role client in API routes.

insert into storage.buckets (id, name, public)
values ('print-files', 'print-files', false)
on conflict (id) do nothing;

-- Service role can do everything. No public access policies needed
-- since all file operations go through server-side API routes that
-- use the service-role client. The anon key cannot read or write
-- this bucket at all.
