import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { verifyStoredDocument } from "@/lib/orderDocument";
import { downloadFile, StorageObjectMissing } from "@/lib/storage";
import { createServiceRoleClient } from "@/lib/supabase/server";
import { createCashfreeOrder, getCashfreeConfig, CashfreeError } from "@/lib/cashfree";
import { controlsFrom, orderingBlock } from "@/lib/shopControls";
import { allowRequest, clientIp, ORDER_RATE_LIMIT, RATE_LIMITED_MESSAGE } from "@/lib/rateLimit";
import { priceSpec, pricingConfigFrom } from "@/lib/orderEdit";
import { selectPrinterForShop } from "@/lib/printerSelection";
import { MAX_COLOR_RANGES } from "@/lib/pageRange";
import { outstandingPayment, PAYMENT_COLUMNS, type PaymentRow } from "@/lib/orderMoney";

const orderSchema = z.object({
  shopId: z.string().uuid(),
  fileStoragePath: z.string().min(1),
  originalFilename: z.string().min(1),
  // Still accepted so existing clients keep working, but never used for
  // anything billed or printed: the server establishes all three from the
  // stored file itself. See src/lib/orderDocument.ts.
  mimeType: z.string().optional(),
  sizeBytes: z.number().int().optional(),
  pageCount: z.number().int().optional(),
  copies: z.number().int().min(1).max(500),
  colorMode: z.enum(["bw", "color"]),
  paperSize: z.enum(["A4", "A3"]),
  orientation: z.enum(["portrait", "landscape", "auto"]),
  sides: z.enum(["single", "double"]),
  pageRange: z.string().min(1),
  /** Pages that print in the other colour mode, e.g. [{range:"3-4", mode:"color"}]. */
  colorRanges: z
    .array(z.object({ range: z.string().min(1).max(200), mode: z.enum(["bw", "color"]) }))
    .max(MAX_COLOR_RANGES)
    .nullish(),
  fitMode: z.enum(["fit", "actual"]).optional(),
  /**
   * One per checkout attempt, generated by the browser. A double-tapped Pay
   * button, or Back then Pay again, sends the same key and gets the same
   * order back instead of a second one.
   */
  idempotencyKey: z.string().uuid().optional(),
});

type ShopRow = { id: string; shop_name: string; status: string; slug: string };

export async function POST(req: NextRequest) {
  const parsed = orderSchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid order data." }, { status: 400 });
  }
  const data = parsed.data;

  const supabase = createServiceRoleClient();

  // 1. Verify shop is active
  const { data: shop } = await supabase
    .from("shops")
    .select("id, shop_name, status, slug")
    .eq("id", data.shopId)
    .single();

  if (!shop || shop.status !== "active") {
    return NextResponse.json({ error: "Shop not found or inactive." }, { status: 404 });
  }

  // 2. A retry of an order that already exists returns that order. Checked
  // before the rate limit and the open/closed switches: the customer already
  // placed it, and a double tap must not turn into an error.
  if (data.idempotencyKey) {
    const existing = await findExisting(supabase, data.shopId, data.idempotencyKey);
    if (existing) return existingOrderResponse(supabase, existing, shop as ShopRow);
  }

  // 3. Too many orders from one address for one shop.
  if (!(await allowRequest(supabase, ORDER_RATE_LIMIT, data.shopId, clientIp(req.headers)))) {
    return NextResponse.json({ error: RATE_LIMITED_MESSAGE, code: "rate_limited" }, { status: 429 });
  }

  // 4. The owner's own switches, re-checked here whatever the page showed.
  const { data: settings } = await supabase
    .from("shop_settings")
    .select("upi_id, payment_gateway, shop_open, accepting_orders, printing_mode")
    .eq("shop_id", data.shopId)
    .single();

  const controls = controlsFrom(settings);
  const blocked = orderingBlock(controls);
  if (blocked) {
    return NextResponse.json({ error: blocked.message, code: blocked.code }, { status: 403 });
  }

  // 5. Load pricing config
  const { data: pricing } = await supabase
    .from("pricing")
    .select("*")
    .eq("shop_id", data.shopId)
    .single();

  if (!pricing) {
    return NextResponse.json({ error: "Shop pricing not configured." }, { status: 404 });
  }

  // 6. Double-sided only where the shop's chosen printer can do it. A shop
  // whose agent has not reported a printer yet is not refused: there is
  // nothing to check against.
  if (data.sides === "double") {
    const { data: printers } = await supabase
      .from("printers")
      .select("id, shop_id, system_name, display_name, is_default, is_enabled, supports_color, supports_duplex, agent_id, last_status")
      .eq("shop_id", data.shopId);
    const selection = selectPrinterForShop(printers ?? [], data.shopId);
    if (selection.ok && !selection.printer.supportsDuplex) {
      return NextResponse.json(
        { error: "Double-sided printing isn't available at this shop right now. Choose single-sided." },
        { status: 422 }
      );
    }
  }

  // 7. Establish what was actually uploaded. The page count, size and type
  // all come from the stored object -- never from the request -- because they
  // decide the price and what the agent prints. The client's pageCount used to
  // be trusted here, which let a 100-page PDF be ordered as one page.
  let documentFacts;
  try {
    documentFacts = await verifyStoredDocument(
      data.shopId,
      data.fileStoragePath,
      downloadFile,
      (err) => err instanceof StorageObjectMissing
    );
  } catch (err) {
    console.error(
      `[orders] shop=${data.shopId} could not read upload: ${err instanceof Error ? err.message : err}`
    );
    return NextResponse.json(
      { error: "We couldn't read your upload just now. Please try again." },
      { status: 503 }
    );
  }

  if (!documentFacts.ok) {
    return NextResponse.json(
      { error: documentFacts.message, code: documentFacts.code },
      { status: documentFacts.code === "bad_path" ? 400 : 422 }
    );
  }

  // 8. Server-authoritative price, against the REAL page count. The same
  // priceSpec prices an owner's edit, so the two can never disagree. What is
  // stored is exactly what was priced — page range and per-page colour — so
  // the agent cannot print more, or more colour, than was paid for.
  const priced = priceSpec(
    {
      copies: data.copies,
      colorMode: data.colorMode,
      paperSize: data.paperSize,
      sides: data.sides,
      orientation: data.orientation,
      pageRange: data.pageRange,
      colorRanges: data.colorRanges ?? null,
      fitMode: data.fitMode ?? "fit",
    },
    documentFacts.pageCount,
    pricingConfigFrom(pricing)
  );
  if (!priced.ok) {
    return NextResponse.json({ error: priced.error }, { status: 422 });
  }
  const breakdown = priced.breakdown;

  const approval = controls.printingMode === "approval_required";
  const gateway = settings?.payment_gateway ?? null;

  // 9. Create order row
  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      shop_id: data.shopId,
      color_mode: data.colorMode,
      paper_size: data.paperSize,
      orientation: data.orientation,
      sides: data.sides,
      copies: data.copies,
      page_range: priced.storedRange,
      page_count: priced.selectedPages.length,
      color_ranges: priced.colorRanges,
      fit_mode: data.fitMode ?? "fit",
      price_breakdown: breakdown,
      amount: breakdown.total,
      payment_status: "pending",
      // Approval mode: nothing is payable until the owner says yes.
      print_status: approval ? "pending_approval" : "payment_pending",
      idempotency_key: data.idempotencyKey ?? null,
    })
    .select("id, public_order_id, customer_session_token, print_status, amount, shop_id")
    .single();

  if (orderError || !order) {
    // Two taps raced past the lookup above; the unique index caught the
    // second. Hand back the order the first one created.
    if (orderError?.code === "23505" && data.idempotencyKey) {
      const existing = await findExisting(supabase, data.shopId, data.idempotencyKey);
      if (existing) return existingOrderResponse(supabase, existing, shop as ShopRow);
    }
    return NextResponse.json(
      { error: "Failed to create order." },
      { status: 500 }
    );
  }

  // 10. Create order_files row
  // Type and size are the server's measurements. The filename is the
  // customer's, kept for display only -- the agent sanitises it before it
  // ever touches a disk.
  await supabase.from("order_files").insert({
    order_id: order.id,
    original_filename: data.originalFilename.slice(0, 255),
    storage_path: data.fileStoragePath,
    mime_type: documentFacts.mimeType,
    size_bytes: documentFacts.sizeBytes,
  });

  // 11. Create payment row. A Cashfree shop's row carries the Cashfree order
  // id from the start, so an approval-mode order gets its checkout on
  // approval under the same id.
  await supabase.from("payments").insert({
    order_id: order.id,
    method: gateway === "cashfree" ? "gateway" : "upi_intent",
    gateway: gateway === "cashfree" ? "cashfree" : null,
    cashfree_order_id: gateway === "cashfree" ? order.id : null,
    purpose: "order",
    amount: breakdown.total,
    status: "pending",
  });

  // 12. Create print_jobs row (won't be claimed until paid — or, in approval
  // mode, until approved and then paid)
  await supabase.from("print_jobs").insert({
    order_id: order.id,
    state: approval ? "PENDING_APPROVAL" : "CREATED",
  });

  const base = {
    orderId: order.public_order_id,
    orderUuid: order.id,
    customerSessionToken: order.customer_session_token,
    amount: breakdown.total,
    breakdown,
    selectedPages: priced.selectedPages,
  };

  if (approval) {
    return NextResponse.json({
      ...base,
      status: "pending_approval",
      gateway: gateway === "cashfree" ? "cashfree" : "none",
      paymentSessionId: null,
      upiLink: null,
    });
  }

  // 13. Payment: the shop chooses its own rail in dashboard settings.
  if (gateway === "cashfree") {
    const config = getCashfreeConfig();
    if (!config) {
      return NextResponse.json(
        { error: "This shop's online payments aren't configured yet." },
        { status: 503 }
      );
    }

    const appUrl = (process.env.NEXT_PUBLIC_APP_URL || "").replace(/\/$/, "");
    try {
      const cf = await createCashfreeOrder(
        {
          // Our order UUID doubles as Cashfree's order_id so the webhook,
          // which echoes only `data.order.order_id`, can find this row again.
          orderUuid: order.id,
          amount: breakdown.total,
          customerPhone: process.env.CASHFREE_PLACEHOLDER_PHONE?.trim() || "9999999999",
          returnUrl: `${appUrl}/p/${shop.slug}?cf_return=1`,
          notifyUrl: `${appUrl}/api/payments/cashfree/webhook`,
        },
        config
      );

      await supabase
        .from("payments")
        .update({
          gateway_order_id: cf.cfOrderId || null,
          payment_session_id: cf.paymentSessionId,
        })
        .eq("order_id", order.id)
        .eq("cashfree_order_id", order.id);

      return NextResponse.json({
        ...base,
        gateway: "cashfree",
        paymentSessionId: cf.paymentSessionId,
        upiLink: null,
      });
    } catch (err) {
      const message =
        err instanceof CashfreeError ? err.message : "Could not start the payment.";
      console.error(`[orders] cashfree setup failed for order=${order.id}: ${message}`);
      // The order exists. Returning it (with the error) lets the customer's
      // status page offer "Pay now", which retries the session, instead of
      // leaving an order they can neither see nor pay.
      return NextResponse.json(
        { ...base, error: message, gateway: "cashfree", paymentSessionId: null, upiLink: null, paymentError: message },
        { status: 502 }
      );
    }
  }

  // Razorpay is modelled in the schema but not wired yet; fall through to the
  // UPI-intent behaviour rather than pretending it works.

  // Default path, unchanged: a UPI intent link the customer pays directly,
  // confirmed by the shop owner in the dashboard.
  const upiId = settings?.upi_id || "";
  const upiLink = upiId
    ? `upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(shop.shop_name)}&am=${breakdown.total}&tn=${order.public_order_id}`
    : null;

  return NextResponse.json({
    ...base,
    upiLink,
    gateway: "none",
    paymentMethod: upiId ? "upi_intent" : "manual",
  });
}

type ExistingOrder = {
  id: string;
  public_order_id: string;
  customer_session_token: string;
  print_status: string;
  amount: number | string;
  shop_id: string;
};

async function findExisting(
  supabase: ReturnType<typeof createServiceRoleClient>,
  shopId: string,
  key: string
): Promise<ExistingOrder | null> {
  const { data } = await supabase
    .from("orders")
    .select("id, public_order_id, customer_session_token, print_status, amount, shop_id")
    .eq("shop_id", shopId)
    .eq("idempotency_key", key)
    .maybeSingle();
  return (data as ExistingOrder | null) ?? null;
}

/** The same response the first request got, rebuilt from what was stored. */
async function existingOrderResponse(
  supabase: ReturnType<typeof createServiceRoleClient>,
  order: ExistingOrder,
  shop: ShopRow
) {
  const [{ data: payments }, { data: settings }] = await Promise.all([
    supabase.from("payments").select(PAYMENT_COLUMNS).eq("order_id", order.id),
    supabase.from("shop_settings").select("upi_id, payment_gateway").eq("shop_id", order.shop_id).maybeSingle(),
  ]);
  const current = outstandingPayment((payments ?? []) as PaymentRow[]);
  const amount = Number(order.amount);
  const cashfree = settings?.payment_gateway === "cashfree";
  const upiId = settings?.upi_id || "";

  return NextResponse.json({
    orderId: order.public_order_id,
    orderUuid: order.id,
    customerSessionToken: order.customer_session_token,
    amount,
    duplicate: true,
    ...(order.print_status === "pending_approval" ? { status: "pending_approval" } : {}),
    gateway: cashfree ? "cashfree" : "none",
    paymentSessionId: cashfree ? (current?.payment_session_id ?? null) : null,
    upiLink:
      !cashfree && upiId && order.print_status !== "pending_approval"
        ? `upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(shop.shop_name)}&am=${amount}&tn=${order.public_order_id}`
        : null,
  });
}
