"""
Build-time artefacts that are generated rather than committed.

Two files PyInstaller wants exist only to make the built executable look like
a real Windows program:

  - file_version_info.txt gives PrintQAgent.exe its Properties > Details tab,
    so the shop sees a named, versioned publisher instead of a blank binary
    that antivirus heuristics dislike;
  - printq.ico gives it an icon.

Both are derived from version.py so they can never disagree with what the
agent reports to the server. Generated at build time rather than committed
because a checked-in copy is one more thing to forget to bump.

Run:  python build_support.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from version import AGENT_NAME, AGENT_VERSION

HERE = Path(__file__).resolve().parent

COMPANY = "PrintQ"
DESCRIPTION = "PrintQ Agent - connects this computer to PrintQ printing"
COPYRIGHT = "PrintQ"


def version_tuple() -> tuple[int, int, int, int]:
    """Windows version resources are always four numbers."""
    parts = [int(p) for p in AGENT_VERSION.split(".") if p.isdigit()]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])  # type: ignore[return-value]


def write_version_info(target: Path | None = None) -> Path:
    target = target or (HERE / "file_version_info.txt")
    major, minor, patch, build = version_tuple()

    target.write_text(
        f"""# Generated by build_support.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{COMPANY}'),
          StringStruct('FileDescription', '{DESCRIPTION}'),
          StringStruct('FileVersion', '{AGENT_VERSION}'),
          StringStruct('InternalName', 'PrintQAgent'),
          StringStruct('LegalCopyright', '{COPYRIGHT}'),
          StringStruct('OriginalFilename', 'PrintQAgent.exe'),
          StringStruct('ProductName', '{AGENT_NAME}'),
          StringStruct('ProductVersion', '{AGENT_VERSION}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""",
        encoding="utf-8",
    )
    return target


def write_icon(target: Path | None = None) -> Path | None:
    """
    Draw the PrintQ mark as a multi-resolution .ico.

    Generated instead of committed so the palette lives in one place. Returns
    None when Pillow is unavailable -- the spec treats the icon as optional,
    and a missing icon must never fail a release build.
    """
    target = target or (HERE / "printq.ico")
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        print("Pillow not available; skipping icon generation.", file=sys.stderr)
        return None

    sizes = [16, 24, 32, 48, 64, 128, 256]
    frames = []
    for size in sizes:
        img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        pad = max(1, size // 16)

        # Ink square with a cyan sheet emerging, echoing the web mark.
        draw.rounded_rectangle(
            [pad, pad, size - pad, size - pad],
            radius=max(2, size // 8),
            fill=(10, 31, 60, 255),
        )
        sheet = size // 4
        draw.rectangle(
            [sheet, sheet + size // 10, size - sheet, size - sheet],
            fill=(0, 152, 199, 255),
        )
        frames.append(img)

    frames[-1].save(target, format="ICO", sizes=[(s, s) for s in sizes])
    return target


def main() -> None:
    info = write_version_info()
    print(f"wrote {info.name} (version {AGENT_VERSION})")
    icon = write_icon()
    print(f"wrote {icon.name}" if icon else "icon skipped")


if __name__ == "__main__":
    main()
